### ISSUE TITLE
Running coverage action in tag push events produce misleading error message

### ISSUE THREAD

**Issue by pdecat** [py-cov-action/python-coverage-comment-action#285]
This [change](https://github.com/py-cov-action/python-coverage-comment-action/pull/248/files#diff-aa416c9a98a0fd16ca04ed4a3606bf634663109cd1562c05467181ad9b0a8a08R174) makes the coverage action produce a misleading error message about permissions, when the issue is that the event triggering the action does not relate to a pull request and/or branch:

```
2023-10-11T13:32:08.2937186Z ##[notice]Starting action
2023-10-11T13:32:08.6275828Z ##[notice]HTTP Request: GET https://api.github.com/repos/claranet/tfwrapper "HTTP/1.1 200 OK"
2023-10-11T13:32:08.6279564Z ##[notice]Generating comment for PR
2023-10-11T13:32:10.0641449Z ##[notice]HTTP Request: GET https://api.github.com/repos/claranet/tfwrapper/contents/data.json?ref=python-coverage-comment-action-data "HTTP/1.1 200 OK"
2023-10-11T13:32:10.0834693Z ##[error]Critical error. This error possibly occurred because the permissions of the workflow are set incorrectly. You can see the correct setting of permissions here: https://github.com/py-cov-action/python-coverage-comment-action#basic-usage
Otherwise please look for open issues or open one in https://github.com/py-cov-action/python-coverage-comment-action/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/coverage_comment/main.py", line 40, in main
    exit_code = action(
                ^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/coverage_comment/main.py", line 92, in action
    return process_pr(
           ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/coverage_comment/main.py", line 180, in process_pr
    assert config.GITHUB_BRANCH_NAME
AssertionError

```

See this execution for example: https://github.com/claranet/tfwrapper/actions/runs/6483246492/job/17604440212#step:5:22

**Comment by pdecat** [comment]
Only happens for tag push events apparently.

**Comment by ewjoachim** [comment]
Ok, looks like rather than an assert, if there's no config.GITHUB_BRANCH_NAME, we should just silently abort.

**Comment by pdecat** [comment]
It's working fine with that branch, thanks! :rocket:

**Comment by pdecat** [comment]
Thank you! :rocket:
