### ISSUE TITLE
coverage_comment.subprocess.SubProcessError:  No data to combine

### ISSUE THREAD

**Issue by rsard-ckt** [py-cov-action/python-coverage-comment-action#472]
Started to face this error without any change in the codebase:

```
Notice: Generating comment for PR
Error: Critical error. This error possibly occurred because the permissions of the workflow are set incorrectly. You can see the correct setting of permissions here: https://github.com/py-cov-action/python-coverage-comment-action#basic-usage
Otherwise please look for open issues or open one in https://github.com/py-cov-action/python-coverage-comment-action/
Traceback (most recent call last):
  File "/workdir/coverage_comment/subprocess.py", line 22, in run
    return subprocess.run(
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('coverage', 'combine')' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workdir/coverage_comment/main.py", line 44, in main
    exit_code = action(
                ^^^^^^^
  File "/workdir/coverage_comment/main.py", line 96, in action
    return process_pr(
           ^^^^^^^^^^^
  File "/workdir/coverage_comment/main.py", line 1[27](https://github.com/energy-solution/iris/actions/runs/10687312738/job/29625509800#step:5:28), in process_pr
    _, coverage = coverage_module.get_coverage_info(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workdir/coverage_comment/coverage.py", line 96, in get_coverage_info
    subprocess.run("coverage", "combine", path=coverage_path)
  File "/workdir/coverage_comment/subprocess.py", line 36, in run
    raise SubProcessError("\n".join([exc.stderr, exc.stdout])) from exc
coverage_comment.subprocess.SubProcessError: 
No data to combine
```

Even after updating the library version to `py-cov-action/python-coverage-comment-action@v3.28`, the error remains.

**Comment by ewjoachim** [comment]
Yep, that's a consequence of [this change](https://github.blog/changelog/2024-08-19-notice-of-upcoming-deprecations-and-breaking-changes-in-github-actions-runners/) by github, tracked in #470 because GitHub loves to break compat in minor versions.

Our readme has been modified. The easiest way to solve this is to add `include-hidden-files: true` to `upload-artifacts`.

**Comment by rsard-ckt** [comment]
Thanks, I'll give it a try.

**Comment by rsard-ckt** [comment]
Worked, thanks!
